class CurrencyPreference {
  const CurrencyPreference({
    required this.code,
    required this.symbol,
    required this.name,
  });

  final String code;
  final String symbol;
  final String name;

  static const CurrencyPreference defaultPreference = CurrencyPreference(
    code: 'NPR',
    symbol: 'NPR',
    name: 'Nepalese Rupee',
  );

  String get displayLabel => '$symbol $code';

  factory CurrencyPreference.fromJson(Map<String, dynamic> json) {
    final code = json['currencyCode'] as String? ?? defaultPreference.code;
    final symbol =
        json['currencySymbol'] as String? ?? defaultPreference.symbol;
    final name = json['currencyName'] as String? ?? defaultPreference.name;
    return CurrencyPreference(code: code, symbol: symbol, name: name);
  }

  Map<String, dynamic> toJson() {
    return {
      'currencyCode': code,
      'currencySymbol': symbol,
      'currencyName': name,
    };
  }
}

const List<CurrencyPreference>
supportedCurrencyPreferences = <CurrencyPreference>[
  CurrencyPreference(code: 'AED', symbol: 'AED', name: 'UAE Dirham'),
  CurrencyPreference(code: 'AFN', symbol: 'AFN', name: 'Afghan Afghani'),
  CurrencyPreference(code: 'ALL', symbol: 'ALL', name: 'Albanian Lek'),
  CurrencyPreference(code: 'AMD', symbol: 'AMD', name: 'Armenian Dram'),
  CurrencyPreference(
    code: 'ANG',
    symbol: 'ANG',
    name: 'Netherlands Antillean Guilder',
  ),
  CurrencyPreference(code: 'AOA', symbol: 'AOA', name: 'Angolan Kwanza'),
  CurrencyPreference(code: 'ARS', symbol: 'ARS', name: 'Argentine Peso'),
  CurrencyPreference(code: 'AUD', symbol: 'A\$', name: 'Australian Dollar'),
  CurrencyPreference(code: 'AWG', symbol: 'AWG', name: 'Aruban Florin'),
  CurrencyPreference(code: 'AZN', symbol: 'AZN', name: 'Azerbaijani Manat'),
  CurrencyPreference(
    code: 'BAM',
    symbol: 'BAM',
    name: 'Bosnia-Herzegovina Convertible Mark',
  ),
  CurrencyPreference(code: 'BBD', symbol: 'BBD', name: 'Barbadian Dollar'),
  CurrencyPreference(code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka'),
  CurrencyPreference(code: 'BGN', symbol: 'BGN', name: 'Bulgarian Lev'),
  CurrencyPreference(code: 'BHD', symbol: 'BHD', name: 'Bahraini Dinar'),
  CurrencyPreference(code: 'BIF', symbol: 'BIF', name: 'Burundian Franc'),
  CurrencyPreference(code: 'BMD', symbol: 'BMD', name: 'Bermudian Dollar'),
  CurrencyPreference(code: 'BND', symbol: 'BND', name: 'Brunei Dollar'),
  CurrencyPreference(code: 'BOB', symbol: 'BOB', name: 'Bolivian Boliviano'),
  CurrencyPreference(code: 'BRL', symbol: 'R\$', name: 'Brazilian Real'),
  CurrencyPreference(code: 'BSD', symbol: 'BSD', name: 'Bahamian Dollar'),
  CurrencyPreference(code: 'BTN', symbol: 'BTN', name: 'Bhutanese Ngultrum'),
  CurrencyPreference(code: 'BWP', symbol: 'BWP', name: 'Botswanan Pula'),
  CurrencyPreference(code: 'BYN', symbol: 'BYN', name: 'Belarusian Ruble'),
  CurrencyPreference(code: 'BZD', symbol: 'BZD', name: 'Belize Dollar'),
  CurrencyPreference(code: 'CAD', symbol: 'C\$', name: 'Canadian Dollar'),
  CurrencyPreference(code: 'CDF', symbol: 'CDF', name: 'Congolese Franc'),
  CurrencyPreference(code: 'CHF', symbol: 'CHF', name: 'Swiss Franc'),
  CurrencyPreference(code: 'CLP', symbol: 'CLP', name: 'Chilean Peso'),
  CurrencyPreference(code: 'CNY', symbol: '¥', name: 'Chinese Yuan'),
  CurrencyPreference(code: 'COP', symbol: 'COP', name: 'Colombian Peso'),
  CurrencyPreference(code: 'CRC', symbol: 'CRC', name: 'Costa Rican Colon'),
  CurrencyPreference(code: 'CUP', symbol: 'CUP', name: 'Cuban Peso'),
  CurrencyPreference(code: 'CVE', symbol: 'CVE', name: 'Cape Verdean Escudo'),
  CurrencyPreference(code: 'CZK', symbol: 'CZK', name: 'Czech Koruna'),
  CurrencyPreference(code: 'DJF', symbol: 'DJF', name: 'Djiboutian Franc'),
  CurrencyPreference(code: 'DKK', symbol: 'DKK', name: 'Danish Krone'),
  CurrencyPreference(code: 'DOP', symbol: 'DOP', name: 'Dominican Peso'),
  CurrencyPreference(code: 'DZD', symbol: 'DZD', name: 'Algerian Dinar'),
  CurrencyPreference(code: 'EGP', symbol: 'EGP', name: 'Egyptian Pound'),
  CurrencyPreference(code: 'ERN', symbol: 'ERN', name: 'Eritrean Nakfa'),
  CurrencyPreference(code: 'ETB', symbol: 'ETB', name: 'Ethiopian Birr'),
  CurrencyPreference(code: 'EUR', symbol: '€', name: 'Euro'),
  CurrencyPreference(code: 'FJD', symbol: 'FJD', name: 'Fijian Dollar'),
  CurrencyPreference(
    code: 'FKP',
    symbol: 'FKP',
    name: 'Falkland Islands Pound',
  ),
  CurrencyPreference(code: 'GBP', symbol: '£', name: 'British Pound'),
  CurrencyPreference(code: 'GEL', symbol: 'GEL', name: 'Georgian Lari'),
  CurrencyPreference(code: 'GHS', symbol: 'GHS', name: 'Ghanaian Cedi'),
  CurrencyPreference(code: 'GIP', symbol: 'GIP', name: 'Gibraltar Pound'),
  CurrencyPreference(code: 'GMD', symbol: 'GMD', name: 'Gambian Dalasi'),
  CurrencyPreference(code: 'GNF', symbol: 'GNF', name: 'Guinean Franc'),
  CurrencyPreference(code: 'GTQ', symbol: 'GTQ', name: 'Guatemalan Quetzal'),
  CurrencyPreference(code: 'GYD', symbol: 'GYD', name: 'Guyanaese Dollar'),
  CurrencyPreference(code: 'HKD', symbol: 'HK\$', name: 'Hong Kong Dollar'),
  CurrencyPreference(code: 'HNL', symbol: 'HNL', name: 'Honduran Lempira'),
  CurrencyPreference(code: 'HTG', symbol: 'HTG', name: 'Haitian Gourde'),
  CurrencyPreference(code: 'HUF', symbol: 'HUF', name: 'Hungarian Forint'),
  CurrencyPreference(code: 'IDR', symbol: 'IDR', name: 'Indonesian Rupiah'),
  CurrencyPreference(code: 'ILS', symbol: '₪', name: 'Israeli New Shekel'),
  CurrencyPreference(code: 'INR', symbol: '₹', name: 'Indian Rupee'),
  CurrencyPreference(code: 'IQD', symbol: 'IQD', name: 'Iraqi Dinar'),
  CurrencyPreference(code: 'IRR', symbol: 'IRR', name: 'Iranian Rial'),
  CurrencyPreference(code: 'ISK', symbol: 'ISK', name: 'Icelandic Krona'),
  CurrencyPreference(code: 'JMD', symbol: 'JMD', name: 'Jamaican Dollar'),
  CurrencyPreference(code: 'JOD', symbol: 'JOD', name: 'Jordanian Dinar'),
  CurrencyPreference(code: 'JPY', symbol: '¥', name: 'Japanese Yen'),
  CurrencyPreference(code: 'KES', symbol: 'KES', name: 'Kenyan Shilling'),
  CurrencyPreference(code: 'KGS', symbol: 'KGS', name: 'Kyrgystani Som'),
  CurrencyPreference(code: 'KHR', symbol: 'KHR', name: 'Cambodian Riel'),
  CurrencyPreference(code: 'KMF', symbol: 'KMF', name: 'Comorian Franc'),
  CurrencyPreference(code: 'KPW', symbol: 'KPW', name: 'North Korean Won'),
  CurrencyPreference(code: 'KRW', symbol: '₩', name: 'South Korean Won'),
  CurrencyPreference(code: 'KWD', symbol: 'KWD', name: 'Kuwaiti Dinar'),
  CurrencyPreference(code: 'KYD', symbol: 'KYD', name: 'Cayman Islands Dollar'),
  CurrencyPreference(code: 'KZT', symbol: 'KZT', name: 'Kazakhstani Tenge'),
  CurrencyPreference(code: 'LAK', symbol: 'LAK', name: 'Laotian Kip'),
  CurrencyPreference(code: 'LBP', symbol: 'LBP', name: 'Lebanese Pound'),
  CurrencyPreference(code: 'LKR', symbol: 'LKR', name: 'Sri Lankan Rupee'),
  CurrencyPreference(code: 'LRD', symbol: 'LRD', name: 'Liberian Dollar'),
  CurrencyPreference(code: 'LSL', symbol: 'LSL', name: 'Lesotho Loti'),
  CurrencyPreference(code: 'LYD', symbol: 'LYD', name: 'Libyan Dinar'),
  CurrencyPreference(code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham'),
  CurrencyPreference(code: 'MDL', symbol: 'MDL', name: 'Moldovan Leu'),
  CurrencyPreference(code: 'MGA', symbol: 'MGA', name: 'Malagasy Ariary'),
  CurrencyPreference(code: 'MKD', symbol: 'MKD', name: 'Macedonian Denar'),
  CurrencyPreference(code: 'MMK', symbol: 'MMK', name: 'Myanmar Kyat'),
  CurrencyPreference(code: 'MNT', symbol: 'MNT', name: 'Mongolian Tugrik'),
  CurrencyPreference(code: 'MOP', symbol: 'MOP', name: 'Macanese Pataca'),
  CurrencyPreference(code: 'MRU', symbol: 'MRU', name: 'Mauritanian Ouguiya'),
  CurrencyPreference(code: 'MUR', symbol: 'MUR', name: 'Mauritian Rupee'),
  CurrencyPreference(code: 'MVR', symbol: 'MVR', name: 'Maldivian Rufiyaa'),
  CurrencyPreference(code: 'MWK', symbol: 'MWK', name: 'Malawian Kwacha'),
  CurrencyPreference(code: 'MXN', symbol: 'MX\$', name: 'Mexican Peso'),
  CurrencyPreference(code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit'),
  CurrencyPreference(code: 'MZN', symbol: 'MZN', name: 'Mozambican Metical'),
  CurrencyPreference(code: 'NAD', symbol: 'NAD', name: 'Namibian Dollar'),
  CurrencyPreference(code: 'NGN', symbol: 'NGN', name: 'Nigerian Naira'),
  CurrencyPreference(code: 'NIO', symbol: 'NIO', name: 'Nicaraguan Cordoba'),
  CurrencyPreference(code: 'NOK', symbol: 'NOK', name: 'Norwegian Krone'),
  CurrencyPreference(code: 'NPR', symbol: 'NPR', name: 'Nepalese Rupee'),
  CurrencyPreference(code: 'NZD', symbol: 'NZ\$', name: 'New Zealand Dollar'),
  CurrencyPreference(code: 'OMR', symbol: 'OMR', name: 'Omani Rial'),
  CurrencyPreference(code: 'PAB', symbol: 'PAB', name: 'Panamanian Balboa'),
  CurrencyPreference(code: 'PEN', symbol: 'PEN', name: 'Peruvian Sol'),
  CurrencyPreference(
    code: 'PGK',
    symbol: 'PGK',
    name: 'Papua New Guinean Kina',
  ),
  CurrencyPreference(code: 'PHP', symbol: '₱', name: 'Philippine Peso'),
  CurrencyPreference(code: 'PKR', symbol: 'PKR', name: 'Pakistani Rupee'),
  CurrencyPreference(code: 'PLN', symbol: 'PLN', name: 'Polish Zloty'),
  CurrencyPreference(code: 'PYG', symbol: 'PYG', name: 'Paraguayan Guarani'),
  CurrencyPreference(code: 'QAR', symbol: 'QAR', name: 'Qatari Riyal'),
  CurrencyPreference(code: 'RON', symbol: 'RON', name: 'Romanian Leu'),
  CurrencyPreference(code: 'RSD', symbol: 'RSD', name: 'Serbian Dinar'),
  CurrencyPreference(code: 'RUB', symbol: '₽', name: 'Russian Ruble'),
  CurrencyPreference(code: 'RWF', symbol: 'RWF', name: 'Rwandan Franc'),
  CurrencyPreference(code: 'SAR', symbol: 'SAR', name: 'Saudi Riyal'),
  CurrencyPreference(
    code: 'SBD',
    symbol: 'SBD',
    name: 'Solomon Islands Dollar',
  ),
  CurrencyPreference(code: 'SCR', symbol: 'SCR', name: 'Seychellois Rupee'),
  CurrencyPreference(code: 'SDG', symbol: 'SDG', name: 'Sudanese Pound'),
  CurrencyPreference(code: 'SEK', symbol: 'SEK', name: 'Swedish Krona'),
  CurrencyPreference(code: 'SGD', symbol: 'S\$', name: 'Singapore Dollar'),
  CurrencyPreference(code: 'SHP', symbol: 'SHP', name: 'Saint Helena Pound'),
  CurrencyPreference(code: 'SLE', symbol: 'SLE', name: 'Sierra Leonean Leone'),
  CurrencyPreference(code: 'SOS', symbol: 'SOS', name: 'Somali Shilling'),
  CurrencyPreference(code: 'SRD', symbol: 'SRD', name: 'Surinamese Dollar'),
  CurrencyPreference(code: 'SSP', symbol: 'SSP', name: 'South Sudanese Pound'),
  CurrencyPreference(
    code: 'STN',
    symbol: 'STN',
    name: 'Sao Tome and Principe Dobra',
  ),
  CurrencyPreference(code: 'SYP', symbol: 'SYP', name: 'Syrian Pound'),
  CurrencyPreference(code: 'SZL', symbol: 'SZL', name: 'Eswatini Lilangeni'),
  CurrencyPreference(code: 'THB', symbol: '฿', name: 'Thai Baht'),
  CurrencyPreference(code: 'TJS', symbol: 'TJS', name: 'Tajikistani Somoni'),
  CurrencyPreference(code: 'TMT', symbol: 'TMT', name: 'Turkmenistani Manat'),
  CurrencyPreference(code: 'TND', symbol: 'TND', name: 'Tunisian Dinar'),
  CurrencyPreference(code: 'TOP', symbol: 'TOP', name: 'Tongan Paanga'),
  CurrencyPreference(code: 'TRY', symbol: '₺', name: 'Turkish Lira'),
  CurrencyPreference(
    code: 'TTD',
    symbol: 'TTD',
    name: 'Trinidad and Tobago Dollar',
  ),
  CurrencyPreference(code: 'TWD', symbol: 'NT\$', name: 'New Taiwan Dollar'),
  CurrencyPreference(code: 'TZS', symbol: 'TZS', name: 'Tanzanian Shilling'),
  CurrencyPreference(code: 'UAH', symbol: 'UAH', name: 'Ukrainian Hryvnia'),
  CurrencyPreference(code: 'UGX', symbol: 'UGX', name: 'Ugandan Shilling'),
  CurrencyPreference(code: 'USD', symbol: '\$', name: 'US Dollar'),
  CurrencyPreference(code: 'UYU', symbol: 'UYU', name: 'Uruguayan Peso'),
  CurrencyPreference(code: 'UZS', symbol: 'UZS', name: 'Uzbekistani Som'),
  CurrencyPreference(code: 'VES', symbol: 'VES', name: 'Venezuelan Bolivar'),
  CurrencyPreference(code: 'VND', symbol: '₫', name: 'Vietnamese Dong'),
  CurrencyPreference(code: 'VUV', symbol: 'VUV', name: 'Vanuatu Vatu'),
  CurrencyPreference(code: 'WST', symbol: 'WST', name: 'Samoan Tala'),
  CurrencyPreference(
    code: 'XAF',
    symbol: 'XAF',
    name: 'Central African CFA Franc',
  ),
  CurrencyPreference(
    code: 'XCD',
    symbol: 'EC\$',
    name: 'East Caribbean Dollar',
  ),
  CurrencyPreference(
    code: 'XOF',
    symbol: 'XOF',
    name: 'West African CFA Franc',
  ),
  CurrencyPreference(code: 'XPF', symbol: 'XPF', name: 'CFP Franc'),
  CurrencyPreference(code: 'YER', symbol: 'YER', name: 'Yemeni Rial'),
  CurrencyPreference(code: 'ZAR', symbol: 'ZAR', name: 'South African Rand'),
  CurrencyPreference(code: 'ZMW', symbol: 'ZMW', name: 'Zambian Kwacha'),
  CurrencyPreference(code: 'ZWL', symbol: 'ZWL', name: 'Zimbabwean Dollar'),
];

CurrencyPreference currencyPreferenceForCode(String code) {
  return supportedCurrencyPreferences.firstWhere(
    (option) => option.code == code,
    orElse: () => CurrencyPreference.defaultPreference,
  );
}
