// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgB8QIPCVe_goDmaX8CEMNmD0J5rj0o38',
    appId: '1:261131547010:web:be06439af062d26ec95f9b',
    messagingSenderId: '261131547010',
    projectId: 'office-buddy-687a4',
    authDomain: 'office-buddy-687a4.firebaseapp.com',
    storageBucket: 'office-buddy-687a4.firebasestorage.app',
    measurementId: 'G-KZQCBLQB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvvvmfERTdDGQATyE5BAB6WTy7oFk8Xs0',
    appId: '1:261131547010:android:f3b3eb436df00c05c95f9b',
    messagingSenderId: '261131547010',
    projectId: 'office-buddy-687a4',
    storageBucket: 'office-buddy-687a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGG5w77HJU-Nn7NC0LOTf0XOWW9hTtWBU',
    appId: '1:261131547010:ios:3d4e37f7f2adfc42c95f9b',
    messagingSenderId: '261131547010',
    projectId: 'office-buddy-687a4',
    storageBucket: 'office-buddy-687a4.firebasestorage.app',
    iosBundleId: 'com.agnepal.officeHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGG5w77HJU-Nn7NC0LOTf0XOWW9hTtWBU',
    appId: '1:261131547010:ios:3d4e37f7f2adfc42c95f9b',
    messagingSenderId: '261131547010',
    projectId: 'office-buddy-687a4',
    storageBucket: 'office-buddy-687a4.firebasestorage.app',
    iosBundleId: 'com.agnepal.officeHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgB8QIPCVe_goDmaX8CEMNmD0J5rj0o38',
    appId: '1:261131547010:web:46f08a032d2cab0ac95f9b',
    messagingSenderId: '261131547010',
    projectId: 'office-buddy-687a4',
    authDomain: 'office-buddy-687a4.firebaseapp.com',
    storageBucket: 'office-buddy-687a4.firebasestorage.app',
    measurementId: 'G-K35ETMC29D',
  );
}
