// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoZlawUj9GtQrL9fLrEaxFCd_YY4-gMnE',
    appId: '1:726861644713:web:eebc96b7777095fc2c7ab8',
    messagingSenderId: '726861644713',
    projectId: 'office-buddy-b4948',
    authDomain: 'office-buddy-b4948.firebaseapp.com',
    storageBucket: 'office-buddy-b4948.firebasestorage.app',
    measurementId: 'G-Z3Y4ZEFLXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2Kwif_zSpR78zRHpB2gGAmhS6Hel2Ik',
    appId: '1:726861644713:android:072359b29d6bd9ba2c7ab8',
    messagingSenderId: '726861644713',
    projectId: 'office-buddy-b4948',
    storageBucket: 'office-buddy-b4948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWCRoh2RBsjfiH-var7OalPE67HHVPYuc',
    appId: '1:726861644713:ios:8eae19338cb857322c7ab8',
    messagingSenderId: '726861644713',
    projectId: 'office-buddy-b4948',
    storageBucket: 'office-buddy-b4948.firebasestorage.app',
    iosBundleId: 'com.medavitech.officebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWCRoh2RBsjfiH-var7OalPE67HHVPYuc',
    appId: '1:726861644713:ios:287fe3bff58214d32c7ab8',
    messagingSenderId: '726861644713',
    projectId: 'office-buddy-b4948',
    storageBucket: 'office-buddy-b4948.firebasestorage.app',
    iosBundleId: 'com.agnepal.officeHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoZlawUj9GtQrL9fLrEaxFCd_YY4-gMnE',
    appId: '1:726861644713:web:a5cc137f930635e32c7ab8',
    messagingSenderId: '726861644713',
    projectId: 'office-buddy-b4948',
    authDomain: 'office-buddy-b4948.firebaseapp.com',
    storageBucket: 'office-buddy-b4948.firebasestorage.app',
    measurementId: 'G-B5BMY5YT24',
  );
}
